### ISSUE TITLE
Expansion

### ISSUE THREAD

**Issue by shkup** [jarethmt/Open-TX-Portal-Voice-Pack#3]
Is there a way to synthesize messages and expand it? To create customized welcome messages from the same theme?

**Comment by shkup** [comment]
Oh found it!
https://glados.c-net.org/

**Comment by jarethmt** [comment]
Oh hell, I didn't know this existed lol. I actually synthesized them myself on Mac by using the "say" command with a specific voice, and then using Melodyne to alter the resulting output to sound like Glad with specific settings (can't remember them off the top of my head), but this is much simpler! Just have to make sure the resultant file is formatted correctly for the Taranis, but this is a great tool! If you want to make a pull request with this link in the README I'd be happy to merge it in!
